// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyvqVqYhw761cE26tt36790CsS_mmXW1k',
    appId: '1:321411949232:web:68413651b4c2b7b96ed175',
    messagingSenderId: '321411949232',
    projectId: 'fd-auth-bloc',
    authDomain: 'fd-auth-bloc.firebaseapp.com',
    storageBucket: 'fd-auth-bloc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9lfbwRwKuDq9iMIUr4T5J6i7EIpcV5zY',
    appId: '1:321411949232:android:8c6b6ad737ef6b386ed175',
    messagingSenderId: '321411949232',
    projectId: 'fd-auth-bloc',
    storageBucket: 'fd-auth-bloc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC--8aWyKsAoFUC-FylbH7RE7s-ZNHQCxc',
    appId: '1:321411949232:ios:55b913caa09b5de36ed175',
    messagingSenderId: '321411949232',
    projectId: 'fd-auth-bloc',
    storageBucket: 'fd-auth-bloc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC--8aWyKsAoFUC-FylbH7RE7s-ZNHQCxc',
    appId: '1:321411949232:ios:55b913caa09b5de36ed175',
    messagingSenderId: '321411949232',
    projectId: 'fd-auth-bloc',
    storageBucket: 'fd-auth-bloc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyvqVqYhw761cE26tt36790CsS_mmXW1k',
    appId: '1:321411949232:web:90b63e6fc4f8f5ba6ed175',
    messagingSenderId: '321411949232',
    projectId: 'fd-auth-bloc',
    authDomain: 'fd-auth-bloc.firebaseapp.com',
    storageBucket: 'fd-auth-bloc.firebasestorage.app',
  );
}
